name: Confirm Flaky Test
on: [push]

jobs:
  flaky-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run the test without NonDex shuffling
        run: mvn -pl apollo-api-impl test -Dtest=com.spotify.apollo.route.MiddlewaresTest#asShouldSerializeObjectAsJson

      - name: Run the test with NonDex shuffling
        run: mvn -pl apollo-api-impl edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.spotify.apollo.route.MiddlewaresTest#asShouldSerializeObjectAsJson -DnondexRuns=10
